// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0A7HT4tHF1dbwag2r8SSFyJrgF7Qk3Bs',
    appId: '1:689211736556:web:2507cb6654319c132a00c9',
    messagingSenderId: '689211736556',
    projectId: 'fir-app-4c517',
    authDomain: 'fir-app-4c517.firebaseapp.com',
    storageBucket: 'fir-app-4c517.firebasestorage.app',
    measurementId: 'G-54SKJ9T07F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBDRaSGRJTSvm6T1bdnWY7wFLi0vM1Nng',
    appId: '1:689211736556:android:3d5fa73f9e51b99a2a00c9',
    messagingSenderId: '689211736556',
    projectId: 'fir-app-4c517',
    storageBucket: 'fir-app-4c517.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn6il0593aCYJpaR-39Dm-zGgpkMEwwaw',
    appId: '1:689211736556:ios:9359362dc535f6b92a00c9',
    messagingSenderId: '689211736556',
    projectId: 'fir-app-4c517',
    storageBucket: 'fir-app-4c517.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );
}
